python3 main.py \
    --data_root train_dataset \
    --train_data_path dogFace_112 \
    --val_data_path dogFace_112 \
    --prefix adaface_ir101_ms1mv2 \
    --gpus 1 \
    --use_16bit \
    --start_from_model_statedict ./epoch=32-step=4191.ckpt \
    --arch ir_101 \
    --evaluate \
    --use_mxrecord \
    --custom_num_class 984
